apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tech-stack: springboot
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
